New uploader readme
KamillaGarifullina/jsdk pull request #1
Opened 2021-12-27 15:59 UTC by KamillaGarifullina

2021-12-30 12:36 UTC, paninebaluy requested changes
* We don't use JS libraries as jQuery anymore --> We don't use JS libraries such as jQuery anymore
* Close to native web platform as possible --> As close to the native web platform as possible
* We are use Shadow DOM --> We use Shadow DOM
* etc --> etc.
* English will be a fallback --> English will be the fallback

2021-12-30 15:58 UTC, rsedykh requested changes
I see it's not yet close, but still left some disturbing comments..

2021-12-30 15:58 UTC, rsedykh commented on uploader/README.md
> +* As close to native web platform as possible. We don't force you to use any specific development environment tools.
Features of uploader? Or if this particular solution? Is SIZE is really #1 reason devs choose ready-made uploaders? What about customer facing features?

2021-12-30 15:58 UTC, rsedykh commented on uploader/README.md
> +* etc.
Versions?

2021-12-30 15:58 UTC, rsedykh commented on uploader/README.md
> +Obtain a Public API Key in your Uploadcare project's dashboard to use file uploading features.
URLs?

2021-12-30 15:58 UTC, rsedykh commented on uploader/README.md
> +For demo-only purposes you can use demopublickey instead.
`demopublickey`?

2021-12-30 15:58 UTC, rsedykh commented on uploader/README.md
> +To integrate Uploadcare widget, first of all, you should connect our script:
Uploader widget? Not uc-uploader? Not upload blocks?

2021-12-30 15:58 UTC, rsedykh commented on uploader/README.md
> +* Evernote
This looks like random order plus it doesn't look nice..

2022-01-11 12:11 UTC, KamillaGarifullina commented on uploader/README.md
> +To integrate Uploadcare widget, first of all, you should connect our script:
Rewritten

2022-01-11 12:11 UTC, KamillaGarifullina commented on uploader/README.md
> +* Evernote
Rewritten

2022-01-11 12:11 UTC, KamillaGarifullina commented on uploader/README.md
> +For demo-only purposes you can use demopublickey instead.
Updated

2022-01-11 12:11 UTC, KamillaGarifullina commented on uploader/README.md
> +* etc.
Rewritten

2022-01-11 12:12 UTC, KamillaGarifullina commented on uploader/README.md
> +Obtain a Public API Key in your Uploadcare project's dashboard to use file uploading features.
Added

2022-01-17 23:29 UTC, rsedykh commented on uploader/README.md
> ++-------------+----------------------+
Не билдится в табличку.

2022-01-17 23:30 UTC, rsedykh requested changes
Оставил пару комментариев к тому, к чему пока можно. Читается тяжело.

И, вопрос — из https://github.com/uploadcare/docs/pull/810/files все полезное взяли?

2022-02-01 09:33 UTC, merged