[JSDK-48] Text editing
KamillaGarifullina/jsdk pull request #2
Opened 2021-12-29 11:24 UTC by KamillaGarifullina

2021-12-30 15:54 UTC, rsedykh requested changes
Didn't have strength to review it properly, but still. (And I'll read it thoroughly later).

2021-12-30 15:54 UTC, rsedykh commented on README.md
> +## 💎 Core concept
concepts?

2021-12-30 15:54 UTC, rsedykh commented on README.md
> +* [upload-blocks](./upload-blocks/) - build your own uploading flow with the simple HTML and CSS.
Please, typography. —, not -.

2021-12-30 15:54 UTC, rsedykh commented on README.md
> +## ⚙️ Installation and startup
startup?

2021-12-30 15:54 UTC, rsedykh commented on upload-blocks/README.md
> +## 🧩 Build your own file uploading flow with the set of pre-defined custom elements!
! at the end?..

2021-12-30 15:54 UTC, rsedykh commented on upload-blocks/README.md
> +We believe - yes, with a power of [Custom Elements standard](https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_custom_elements) and our widget-purpose-specific open-source [Symbiote.j
open-source? Where have you found it?

2021-12-30 15:54 UTC, rsedykh commented on upload-blocks/README.md
> +To integrate the Uploadcare widget, first of all, you should connect our script:
We should definitely ask Natasha to review such changes.  Or to have another reviewer. I can provide one.

2021-12-30 15:54 UTC, rsedykh commented on upload-blocks/README.md
>  ## 🎨 Customize everything!
!!!11

2021-12-30 15:54 UTC, rsedykh commented on upload-blocks/README.md
> +Some of the widget settings in this example are passed via CSS variables. That means you can use styles, CSS classes, and dedicated CSS files to give any setting to any block or redefine if using nat
Somebody forget to clean up after.

2022-01-11 12:15 UTC, KamillaGarifullina commented on upload-blocks/README.md
> +We believe - yes, with a power of [Custom Elements standard](https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_custom_elements) and our widget-purpose-specific open-source [Symbiote.j
Here https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/o/open-source

2022-01-12 09:21 UTC, paninebaluy commented on README.md
> +## 💎 Core concept
concepts

2022-01-12 15:36 UTC, paninebaluy requested changes
There are some questions about the content of this readme. See comments.

2022-01-12 15:36 UTC, paninebaluy commented on upload-blocks/README.md
> +Some of the widget settings in this example are passed via CSS variables. That means you can use styles, CSS classes, and dedicated CSS files to give any setting to any block or redefine if using nat
Also, what did you mean by "native HTML syntax?" Is this about using default browser styling?

2022-01-12 15:36 UTC, paninebaluy commented on upload-blocks/README.md
> +Some of the widget settings in this example are passed via CSS variables. That means you can use styles, CSS classes, and dedicated CSS files to give any setting to any block or redefine if using nat
"... to give any setting to any block or redefine if using native DOM API or just native HTML syntax".
Blocks usually have CSS properties, not settings. And they may be overridden by [styles with greater specificity](https://www.w3schools.com/css/css3_variables_overriding.asp).
I suggest this rewrite of the second sentence:

That means you can use _(inline -- please clarify)_ styles, CSS classes, and dedicated CSS files to give any property to any block or override styles if your project uses native DOM API _(or just native HTML syntax -- to clarify)_.

2022-01-12 15:36 UTC, paninebaluy commented on upload-blocks/README.md
> +Please don't be shy to participate; your opinion is very important for us.
Please don't hesitate to take part; your opinion is very important to us.

2022-01-12 15:36 UTC, paninebaluy commented on upload-blocks/README.md
> +Each block has a reference CSS file, placed at the common directory with the JavaScript class definition module. You can use it as the template to create your own custom styling (or CSS-animations) f
Each block has a reference CSS file that's located in a directory together with a JavaScript class definition module. You can use it as the template to create your own custom styling (or CSS animations) for any library block. All blocks and their children act like regular DOM elements; therefore, you can use native CSS selectors and any existing styling approach. All significant component states are provided as element attribute flags, so you can use the full power of CSS to deeply customize the blocks.

2022-01-12 15:36 UTC, paninebaluy commented on upload-blocks/README.md
> +Block components can be used separately or in combinations. You can compose them into the common workflow:
You can combine them to create a common workflow like this one:

2022-01-12 15:36 UTC, paninebaluy commented on upload-blocks/README.md
> +We believe - yes, with a power of [Custom Elements standard](https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_custom_elements) and our widget-purpose-specific open-source [Symbiote.j
We believe it is &mdash; with the power of [Custom Elements standard](https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_custom_elements) and our widget-purpose-specific open-source [Symbiote.js](https://github.com/symbiotejs/symbiote.js) library.

2022-01-12 15:36 UTC, paninebaluy commented on README.md
> +* Minimum of external dependencies: security audit is not expensive.
* Minimum external dependencies, which makes the security audit really inexpensive.

2022-01-12 15:36 UTC, paninebaluy commented on README.md
> +* Type safety with a JSDoc declaration and TypeScript static analysis.
* Type safety with the JSDoc declaration and the TypeScript static analysis.

2022-01-12 15:36 UTC, paninebaluy commented on README.md
> +* We are trying to be close to the native web platform as possible and don't force you to use any specific development environment tools.
* It's as close to your native web platform as possible and doesn't force you to use any environment-specific development tools.

2022-01-12 15:36 UTC, paninebaluy commented on README.md
> +* Tested by Uploadcare community.
* Tested by the Uploadcare community.

2022-01-12 15:36 UTC, paninebaluy commented on README.md
> +All code in this repository works without any other build process in any modern browser. You can open any HTML file in the project structure to make it work during development or testing purposes. No
You can open any HTML file in the project structure to make it work during the development or testing phase.

2022-01-12 15:36 UTC, paninebaluy commented on upload-blocks/README.md
> +## 🧩 Build your own file uploading flow with the set of pre-defined custom elements!
## 🧩 Use predefined custom elements to build your own file uploading flow

2022-02-15 08:59 UTC, foxeyes approved these changes

2022-02-15 10:50 UTC, merged